name: Deploy to Kubernetes

on:
  push:
    branches:
      - master # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker login -u ${{ secrets.CI_REGISTRY_USER }} -p ${{ secrets.CI_REGISTRY_PASSWORD }} ${{ secrets.CI_REGISTRY }}
          cd k8s/docker/server/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/admin-order-backend:${{ github.sha }} -f Dockerfile .
          docker tag ${{ secrets.CI_REGISTRY }}/admin-order-backend:${{ github.sha }} ${{ secrets.CI_REGISTRY }}/admin-order-backend:${{ github.sha }}:latest
          docker push ${{ secrets.CI_REGISTRY }}/admin-order-backend:${{ github.sha }}
          docker push ${{ secrets.CI_REGISTRY }}/admin-order-backend

      # - name: Set up Kubernetes
      #   uses: azure/setup-kubectl@v1
      #   with:
      #     kubectl-version: "latest"

      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl config set-cluster my-cluster --server=${{ secrets.K8S_SERVER }} --certificate-authority=${{ secrets.K8S_CA }}
      #     kubectl config set-credentials my-user --username=${{ secrets.K8S_USER }} --password=${{ secrets.K8S_PASSWORD }}
      #     kubectl config set-context my-context --cluster=my-cluster --user=my-user
      #     kubectl config use-context my-context
      #     kubectl apply -f k8s/deployment.yaml
      #     kubectl set image deployment/admin-order-backend admin-order-backend=${{ secrets.DOCKER_USERNAME }}/admin-order-backend:${{ github.sha }}
